version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: gold-prices-mongodb
    ports:
      - "27037:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    networks:
      - gold-prices-network

volumes:
  mongodb_data:

networks:
  gold-prices-network:
    driver: bridge 